# -*- coding: utf-8 -*-
"""Untitled43.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GA6awyCHjiKBSId-F4hSro7Nj-VV95Vo
"""

from google.colab import files
import json
import re

# Upload your JSON file
uploaded = files.upload()
filename = list(uploaded.keys())[0]
print(f"📁 Uploaded file: {filename}")

# Load the JSON
with open(filename, 'r') as file:
    data = json.load(file)

# Combine shows and movies into one list
items = []
if 'shows' in data:
    items.extend(data['shows'])
if 'movies' in data:
    items.extend(data['movies'])

# Fallback for flat list
if not items and isinstance(data, list):
    items = data

# Fields to analyze
fields_to_analyze = ["genre", "language", "mood", "awards", "content_type"]

# Containers
unique_titles = set()
unique_years = set()
unique_values = {field: set() for field in fields_to_analyze}

# Regex to extract title and year from "Title (YYYY)"
def extract_title_and_year(twy):
    match = re.match(r"(.+?)\s*\((\d{4})\)", twy)
    if match:
        return match.group(1).strip(), int(match.group(2))
    return twy.strip(), None

# Process items
for item in items:
    twy = item.get("title_with_year", "")
    title, year = extract_title_and_year(twy)
    if title: unique_titles.add(title)
    if year: unique_years.add(year)

    for field in fields_to_analyze:
        val = item.get(field)
        if val:
            if isinstance(val, list):
                unique_values[field].update(val)
            else:
                unique_values[field].add(str(val))

# Results
print(f"\n📊 Total items processed: {len(items)}")
print(f"✅ Entries with 'title_with_year': {sum(1 for i in items if i.get('title_with_year'))}")

print("\n🎬 Unique Titles:")
for title in sorted(unique_titles):
    print(f" - {title}")
print(f"Total: {len(unique_titles)}")

print("\n📅 Unique Years:")
for year in sorted(unique_years):
    print(f" - {year}")
print(f"Total: {len(unique_years)}")

for field, values in unique_values.items():
    print(f"\n📌 Field: {field}")
    print(f"→ Unique values ({len(values)}):")
    for v in sorted(values):
        print(f"  - {v}")

from google.colab import files
import json

# Upload your JSON file
uploaded = files.upload()
filename = list(uploaded.keys())[0]
print(f"Uploaded file: {filename}")

# Load the JSON
with open(filename, 'r') as file:
    data = json.load(file)

# Combine both movies and shows into a single list
items = []
if 'movies' in data:
    items.extend(data['movies'])
if 'shows' in data:
    items.extend(data['shows'])
# If not nested, assume data is already a list
if not items and isinstance(data, list):
    items = data

# Count how many entries have a non-empty title_with_year
count_with_twy = sum(1 for item in items if item.get("title_with_year"))

print(f"📦 Total entries in dataset: {len(items)}")
print(f"✅ Entries with 'title_with_year': {count_with_twy}")